### ISSUE TITLE
Limit symbols exported by shared libraries

### ISSUE THREAD

**Issue by hillu** [libyal/libvshadow#11]
Hi Joachim,

In Debian, shared library packages can contain a `.symbols` file (see _deb-symbols(5)_) that contains information about which versions of a given library export which symbols. This is useful for automatically determining versioned install dependencies in packages containing programs that are linked against a given shared library.

In `libvshadow` (and all the other libyal* packages I maintain for Debian) I noticed that many symbols from your other libraries were also exported, e.g. `libcdata_*`, and put a workaround in place.

But one might as well limit the symbols that are exported when linking the shared library in the first place. This can be done by adding `-export-symbols-regex ^libvshadow_` to `libvshadow_la_LDFLAGS` in libvshadow/Makefile.am 

Do you see any problem with such a change for libvshadow and all the other libraries?

Cheers,
-Hilko

**Comment by joachimmetz** [comment]
> Do you see any problem with such a change for libvshadow and all the other libraries?

Don't think so; the idea is that only the functions in the include header are exported. I'll have a look at cause and correction when time permits.

**Comment by hillu** [comment]
It appears that you intended the `LIBVSHADOW_EXTERN` macro in `include/libvshadow/extern.h` to do this, but there are only definitions for building on Windows. For Linux, you'd probably build with `-fvisibility=hidden` and add a define like this:
```
#define LIBVSHADOW_EXTERN __attribute__((visibility("default")))
```

**Comment by joachimmetz** [comment]
Moved to https://github.com/libyal/libyal/issues/71, seeing it affects more than libvshadow
