### ISSUE TITLE
Add dokany support

### ISSUE THREAD

**Issue by odelamp** [libyal/libvshadow#15]
Hi Joakim,

I'm running into an issue with building libvshadow on Win2012 R2 server.
I compiled Libvshadow using Visual studio Express 2017 and Dokan provided from your Git.
I suppose this is due to the dokan version been too old for Windows2012 but havn't been able to use dokany instead.
Do you have any suggestions?

Thanks.
Olivier.

**Comment by joachimmetz** [comment]
I'm working on the new dokan support. This will depend on time available.

**Comment by joachimmetz** [comment]
This is completed, closing issue.
