### ISSUE TITLE
MinGW compilation can't include FUSE support

### ISSUE THREAD

**Issue by odelamp** [libyal/libvshadow#16]
Hi Joakim,

As the Windows compliation is having trouble with Dokan I was wondering if I can compile using MinGW.

I tried as describled in the Wiki and got the following output at config:
configure:
Building:
   libcerror support:                            local
   libcthreads support:                          local
   libcdata support:                             local
   libclocale support:                           local
   libcnotify support:                           local
   libcsplit support:                            local
   libuna support:                               local
   libcfile support:                             local
   libcpath support:                             local
   libbfio support:                              local
   libfdatetime support:                         local
   libfguid support:                             local
   FUSE support:                                 no

Features:
   Multi-threading support:                      winapi
   Wide character type support:                  yes
   vshadowtools are build as static executables: no
   Python (pyvshadow) support:                   no
   Python version 2 (pyvshadow) support:         no
   Python version 3 (pyvshadow) support:         no
   Verbose output:                               no
   Debug output:                                 no
FUSE support isn't enabled.
I even tried to force it using --with-libfuse=/usr/include
but same results.
looking at the config.log I get the following:
configure:39912: checking whether to use search for libfuse in includedir and libdir or in the specified DIR, or no if not to use libfuse
configure:39919: result: /usr/include
configure:40018: checking fuse.h usability
configure:40018: i686-w64-mingw32-gcc -c  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -I/usr/include/include -I/usr/i686-w64-mingw32/sys-root/mingw/include conftest.c >&5
conftest.c:160:18: fatal error: fuse.h: No such file or directory
 #include <fuse.h>
                  ^
compilation terminated.

Did I missed something?

Thanks for your support.

**Comment by joachimmetz** [comment]
Is there fuse support for MinGW? if so you'll likely need to install the development package as well or otherwise point configure at the right paths to find the include header and the library to link against.

**Comment by joachimmetz** [comment]
No response from original reporter closing issue.
