### ISSUE TITLE
LIBCERROR_DLL_EXPORT: No such file or directory

### ISSUE THREAD

**Issue by ogjelland** [libyal/libvshadow#19]
Seems like there is some inconsistency in the source code for _libvshadow_ right now, compiling on Debian stable I'm getting:

- gcc: error: @LIBCERROR_DLL_EXPORT@: No such file or directory

_synclibs.sh_ is version 20171003.

**Comment by joachimmetz** [comment]
Please read https://github.com/libyal/libvshadow/wiki/Building and use a source distribution package. Only use the git version if you are actively developing libvshadow.

**Comment by joachimmetz** [comment]
Pushed pending dev updates: https://github.com/libyal/libvshadow/commit/20f07217a0f37b1224ad322a65add75832a024ba
