### ISSUE TITLE
display only differences

### ISSUE THREAD

**Issue by odibrowne** [libyal/libvshadow#2]
Would it be possible to add a flag which would mount the shadow volume to show only the files that are included in the shadow volume and not the original volume.

**Comment by joachimmetz** [comment]
Possible yes, in scope of libvshadow, no.

libvshadow focuses on the volume level format only, what you are asking for is something that needs to happen at file system level.

Also why only show files that "included"? Why not deleted or altered files?

**Comment by odibrowne** [comment]
thank you for your reply
