### ISSUE TITLE
libvshadow-alpha-20190112 error on mount

### ISSUE THREAD

**Issue by DominikSchlecht** [libyal/libvshadow#20]
Dear @joachimmetz,
first, thanks for this great library and all your other projects :+1:

I was migrating from the 20181216 version to 20190112 when I encountered the following error occurring on mounting the vss snapshots from an ewf:
```
./vshadowmount /mnt/ewf/ewf1 /mnt/vss
vshadowmount 20190112

Unable to open source volume
libvshadow_volume_get_store: invalid store value already set.
mount_handle_open: unable to retrieve input: 1 from input volume.
```

vshadowinfo runs without errors, also in the 2018-Version everything, including the mount, works fine. Both versions (2018 and 2019) are compiled from the release-page on an up-to-date Ubuntu 16 LTS machine. Compilation shows no errors.

Have you encountered this error in the past? Do you need more information?

Greetings,
Dominik

**Comment by joachimmetz** [comment]
thx, for the report, I've not encountered this yet, the mount tool was recently updated to support DokanY, maybe a bug was introduced.

I will have a look as soon as time permits.

**Comment by ptMuta** [comment]
Can confirm. This bug appeared on the latest release. Building the december release worked.

Sadly I didn't have more time to debug, but you can replicate it by running it on linux (eg, debian) against a ewf mounted E01 file.

**Comment by joachimmetz** [comment]
Issue is that the mount tool hits a safe guard after the first vss. I'll push an updated version later.
