### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Adfighting** [libyal/libvshadow#21]
Hi,
i want to use libvshadow and libewf both, but they are in conflict because they have libcdata(when i use both libshadow.a and libewf.a),
could you please tell me how to compile? 
thanks  !!!

**Comment by joachimmetz** [comment]
So both are licensed LGPL, so if you want to use it in a commercial tool you'll have to build a shared object (so or dll) of (both of) them instead.

Otherwise it will highly depend how you link them together in your application. You'll need to provide more details for me to give you any useful input.

**Comment by Adfighting** [comment]
Hi,Joachim
Thanks for replying!!!
When I compile the program, there will always be mistakes :
D:/mysys/msys64_1/mingw64/lib/libvshadow.a(libcdata_tree_node.o):libcdata_tree_node.c:(.text+0x3a45): multiple definition of `libcdata_tree_node_get_leaf_node_list'
D:/mysys/msys64_1/mingw64/lib/libewf.a(libcdata_tree_node.o):libcdata_tree_node.c:(.text+0x2680): first defined here
Now, I want to use libcdata that already compiled to compile libvshadow, Can i set configure to do it.
In addition, I wonder if different versions will have any impact?
thanks!!!

**Comment by joachimmetz** [comment]
what are you linking against?

* if you want them both in a single program as static libraries (.a) then you must create a single project that contains all dependencies only once. You've now created 2x link time libraries that contain overlapping code
* if you want DLLs (which is recommended so you can easily update a library with newer versions) you'll have to build DLLs (either with configure or the visual studio solution files)

**Comment by Adfighting** [comment]
I downloaded your libewf, libvshadow, libbde, libfsapfs, libvhdi, libvmdk and so on. Then I compiled them and took out the static libraries. In my own program, I used the interface you provided. When I tested the interface program, I used the following compilation command: G + + main.c - I / mingw64 / include - L / mingw64 / lib - ltsk - lewf - lvshadow - lbfio - lbde - lzstd - lvmdk - lqcow - L vhdi -lvdi -lafflib -lcrypto -lwsock32 -g -O0

**Comment by joachimmetz** [comment]
I see, unfortunately that is not going to work. 

1. you can statically link against the individual libraries and their dependencies, but you have to ensure each one (of the dependencies) is included only once
2. you can link against them as shared libraries

**Comment by Adfighting** [comment]
Mm-hmm, yes, there is multiple inclusion, so I want to compile all public libraries first, and then use the compiled public libraries directly when compiling such libraries as libvshadow.

Building:
libcerror support: local
libcthreads support: local
libcdata support: local
libclocale support: local
libcnotify support: local
libcsplit support: local
libuna support: local
libcfile support: local
libcpath support: local

So would you like to ask me if I can set the building to rely on the public library compiled by myself instead of the items in the installation package you designed (as above,depending on the package you designed)?
thanks !! thanks!!

**Comment by joachimmetz** [comment]
Since you want to link statically you technically do not have "public" (shared) libraries (If I assume correctly what you mean with public). You only have libraries that are used internally ("private")

You'll need to create a link command (directly or using some build script) that includes libvshadow, and its dependencies such as libcerror, libcthreads, etc and their dependencies like pthread into a single link command.

**Comment by Adfighting** [comment]
As you said, I will try to do it.
Listen to what you said, I got a lot, thank you.

**Comment by joachimmetz** [comment]
If instead, you want to use them as shared ("public") libraries compile them as such (`./configure --enable-shared=yes`) and link against them with `CFLAGS=-DLIBVSHADOW_DLL_IMPORT` (and equiv)

**Comment by joachimmetz** [comment]
No update from original reporter, assuming question has been answered, closing issue.
