### ISSUE TITLE
Noob needs assistance

### ISSUE THREAD

**Issue by cmasonartz** [libyal/libvshadow#24]
I am not cognizant of how to use the files in the folder.

Have: Ubuntu 20.04 64-bit: updated as of 9/25/2020
Python3 is installed.
The libvshadow tar is downloaded and unpacked in my Downloads folder.
I understand how to navigate Ubuntu and Windows based operating environments if that matters.

Need: detailed instructions on how to get the application to work. I have tried using the sh scripts and i am absolutely clueless as to what to do. Am i supposed to install the program? am i supposed to compile it first? I do not know what i have and what to do. What has been provided in the Git always delivers errors of some kind that i cannot rectify. Mercy. I need help please. I understand that the Github is probably for advanced users, though i am interested in libvshadow for uncovering lost files on NTFS drives. 

Any help is appreciated. Thank you!

**Comment by joachimmetz** [comment]
> I understand that the Github is probably for advanced users, 

The github project is focused on the development and maintenance of the project mainlyl

> though i am interested in libvshadow for uncovering lost files on NTFS drives.

First of all libvshadow only focuses on the volsnap VSS format, it allows you to exposes snapshots as volumes that can be mounted with ntfs3g. So it depends on what you mean with "uncovering lost files" how relevant libvshadow for that purpose will be. Also see: https://github.com/libyal/libvshadow/wiki/Mounting

> am i supposed to compile it first? 

If you downloaded the source then yes you need to compile it first. Building instruction can be found here https://github.com/libyal/libvshadow/wiki/Building.

For Ubuntu 18.04 and 20.04 a precompiled version is provided in https://launchpad.net/~gift/+archive/ubuntu/stable (libvshadow-tools package)

**Comment by cmasonartz** [comment]
Greetings Joachim Metz,

Thank you for your invaluable assistance.

Continuing on being new to using github….here’s where I am at.
I found the proper .deb packages. I downloaded them. I let ubuntu install them using the software manager.

Now that i have that accomplished. 1. How do I use the command? It doesn’t work as an actual command in the terminal. (OR) 2. Do I need to follow the directions to the letter as specified in the wiki?
3. is there a command line syntax I am not aware of?

Sorry for bugging you, but I am grateful

Thanks,
Clinton

**Comment by joachimmetz** [comment]
> 1. How do I use the command? It doesn’t work as an actual command in the terminal. (OR)

if you installed `libvshadow-tools` you should have `vshadowinfo` and `vshadowmount` tools installed on your system.
These should be run from a Linux terminal

> 2. Do I need to follow the directions to the letter as specified in the wiki?

yes, but they do expect you to are somewhat familiar with running tools on a Linux terminal

> 3. is there a command line syntax I am not aware of?

`-h` for help maybe ?

**Comment by joachimmetz** [comment]
No update from original reporter, assuming question is answered, closing issue.
