### ISSUE TITLE
Initial volume open/read time consuming on some VSS

### ISSUE THREAD

**Issue by jimuk** [libyal/libvshadow#26]
I am doing some experiments with Libvshadow and following recent changes can now open volumes successfully and read data.

However, I have found that the first call to read data can be very slow (sometimes over 20 seconds). This is accompanied by a significant increase in memory footprint. Presumably, this is because the library is building a map of the cached data blocks?

I have tried the following three methods to read data with the same results:

libvshadow_store_read_buffer_from_file_io_handle()
libvshadow_store_read_buffer()
libvshadow_store_read_buffer_at_offset()

Please can I check:

1. Am I correct that the three methods about are really just different ways to achieve the same thing?

2. Is the slow start-up expected and is there anything that could be done to improve it please?

Thank you,

Jim

**Comment by joachimmetz** [comment]
> Presumably, this is because the library is building a map of the cached data blocks?
> Is the slow start-up expected and is there anything that could be done to improve it please?

Yes, the initial read of a large/complex snapshot can be time consuming.
you could code profile to determine where the bottle neck is

I still need to look at optimizing this but has low priority on my to do list. 

https://github.com/log2timeline/plaso/issues/1887

> Am I correct that the three methods about are really just different ways to achieve the same thing?

> libvshadow_store_read_buffer()
> libvshadow_store_read_buffer_at_offset()

yes these serve a similar purpose

> libvshadow_store_read_buffer_from_file_io_handle()

this is to allow a read from a separate BFIO file_io_handle, in case you want to parallelize reading from multiple file handles/objects, but same purpose

**Comment by jimuk** [comment]
Thank you. I will try to figure out why it is happening.

**Comment by joachimmetz** [comment]
No update from original reporter, some performance tweaks in libyal/libvshadow@b3d35c2 . Closing issue for now, reopen if more information becomes available.
