### ISSUE TITLE
vshadowmount: No sub system to mount VSS format

### ISSUE THREAD

**Issue by frankwxu** [libyal/libvshadow#27]
The DD image is from https://www.cfreds.nist.gov/data_leakage_case/data-leakage-case.html

vshadowinfo works, but vshadowinfo doesn't

![image](https://user-images.githubusercontent.com/1145258/101856792-06999a00-3b34-11eb-9242-8c0700e5bab1.png)

![image](https://user-images.githubusercontent.com/1145258/101856876-35177500-3b34-11eb-8a8c-06e8049a8d02.png)

**Comment by joachimmetz** [comment]
See: https://github.com/libyal/libvshadow/wiki/Mounting#mounting

**Comment by frankwxu** [comment]
Thanks. I install libfuse-dev and recompile it. It is working now.

![image](https://user-images.githubusercontent.com/1145258/101915854-2d87b880-3b94-11eb-9e95-de6316669ab7.png)

**Comment by joachimmetz** [comment]
ack, issue seems to be resolved, closing issue
