### ISSUE TITLE
Packages needed for building on Fedora

### ISSUE THREAD

**Issue by countingpine** [libyal/libvshadow#28]
According to the [Wiki](https://github.com/libyal/libvshadow/wiki/Building), Debian needs `sudo apt install git autoconf automake autopoint libtool pkg-config`.

I've found that Fedora can work with the following roughly equivalent set of packages (although on my system it seems like git and pkg-config were preinstalled):

    sudo yum install git autoconf automake gettext-devel libtool pkg-config

Just thought this might be worth adding to the Wiki.

**Comment by joachimmetz** [comment]
@countingpine thx for the suggestion I'll have a look adding this when time permits, note that `dnf` is now the preferred Fedora package manager to my knowledge

**Comment by countingpine** [comment]
Thanks.  My usual RHEL distro is actually CentOS 7, where `dnf` doesn't seem to be bundled, so I don't think it's quite at the `apt-get` stage of deprecation yet.

**Comment by joachimmetz** [comment]
> Thanks. My usual RHEL distro is actually CentOS 7, where dnf doesn't seem to be bundled, so I don't think it's quite at the apt-get stage of deprecation yet.

I'll add Fedora instructions for now, looks like CentOS 8 introduces dnf.

Changes to the templates in https://github.com/libyal/libyal/commit/91aecdbf880e9bbc60867556171b2b579c353a56 and wiki pages have been updated: https://github.com/libyal/libvshadow/wiki/Building/_history

closing issue.
