### ISSUE TITLE
Why is there a limit of 99 stores?

### ISSUE THREAD

**Issue by mnrkbys** [libyal/libvshadow#29]
libvshadow does not appear to support more than 100 snapshots.
The relevant line of source code is quoted below.

https://github.com/libyal/libvshadow/blob/ee8681dc97db9f0e62b9b7cd153229caaafb0e0c/vshadowtools/mount_file_entry.c#L675

Windows Server creates snapshots frequently, so more than 100 snapshots may be created.
What is the reason for setting the maximum number of snapshots to 100?

**Comment by joachimmetz** [comment]
> What is the reason for setting the maximum number of snapshots to 100?

With parsing proprietary formats, having safe guards makes sense to prevent misinterpretation. Can you share your test data?

**Comment by joachimmetz** [comment]
would appreciated reproducible test data, not just observations.

**Comment by mnrkbys** [comment]
I do not currently have such a disk image, but I believe it is possible to intentionally create a disk image containing 100+ snapshots with a command.
Can it meet your requirements?

**Comment by joachimmetz** [comment]
> Can it meet your requirements?

Yes, you can use/modify https://github.com/dfirlabs/vss-specimens to generate it.

**Comment by mnrkbys** [comment]
Wow, nice script. Thanks for sharing.
As soon as I have some free time, I will create a disk image for testing.

**Comment by mnrkbys** [comment]
Hi, I have uploaded a disk image which has 110 snapshots.
Are there any deficiencies as test data?
[ntfs_with_110_vss.zip](https://github.com/libyal/libvshadow/files/9826693/ntfs_with_110_vss.zip)

The version of vshadow.exe is 3.0.
```
C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64>vshadow.exe

VSHADOW.EXE 3.0 - Volume Shadow Copy sample client.
Copyright (C) 2005 Microsoft Corporation. All rights reserved.
```

**Comment by joachimmetz** [comment]
thx I'll have a look, what would be realistic new upper bound? 199? 499? 999?

realize that every mounted store will consume memory

**Comment by mnrkbys** [comment]
I think the realistic snapshot limit is 299.
If you feel this value is too large, then 199 would be fine.
Also, although it may be against the implementation policy, could you consider specifying the upper limit as a command option?

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libvshadow/commit/3d8edda8c9f738adb38325d514672cb309869ef4
