### ISSUE TITLE
Support for snapshot description (custom name for the restore point)?

### ISSUE THREAD

**Issue by ArtyomAfanasovBS** [libyal/libvshadow#30]
Are there plans to add the ability to retrieve a snapshot description that is set by the user when creating a restore point?

I did some research, but all I was able to accomplish was to find the relationship between the snapshot name and the snapshot itself (by storage ID), and a few other things. But I couldn't find an offset indicating the structure of the snapshot name. I'm sure it's possible to avoid using disk signature carving (carving is a long process): Windows is very fast at finding snapshot names when requesting a system restore through the user interface.
I have attached a description of the part of the snapshot name structure that I am investigating.

Each such structure starts with 8F11E16A1A59E047B2C33CFA26EC2B80 (constant across all snapshots and all machines). Unknown byte sequences are marked in yellow, but they are constant across snapshots and machines. From these constant signatures it is possible to find the name structure using carving.
Using Shadow copy set identifier and Shadow copy identifier, it is possible to associate a snapshot name with a specific snapshot.
Snapshot creation time refers to the snapshot creation time, which is displayed in the Windows UI during system recovery (libvshadow extracts from Catalog entry type 0x02 a creation time that differs by a few seconds from the Snapshot creation time).
Next is the length of the snapshot description (name) and the description itself (name).

Researched structure:
![Researched structure](https://github.com/libyal/libvshadow/assets/79638564/e55668c2-8892-4848-b203-31199335c92f)

Store Information format:
![Store information general](https://github.com/libyal/libvshadow/assets/79638564/3184b130-170b-41d0-bcff-4b08ea06644b)

Example of the Store Information:
![Store information](https://github.com/libyal/libvshadow/assets/79638564/d1022a82-6bbf-426a-9530-7cc40a831ddf)

**Comment by ArtyomAfanasovBS** [comment]
Windows UI for system restoring:
![image](https://github.com/libyal/libvshadow/assets/79638564/bdcff9a5-6795-48c3-943d-c418e9f5650c)

**Comment by ArtyomAfanasovBS** [comment]
>Are you sure these are part of the volume layer data structures?
No, I am not sure. But the presence of a snapshot identifier in the discovered name structure indicates a relationship between the snapshot (namely the Store Information structure) and Name structure (similar to the relationship between Volume Shadow Snaphots structures).

>Or is this operating system level information stored elsewhere, such as Windows Registry?
That is a good idea! I will think about it.

One of my goals is to find the names of the snapshots in the E01 image containing NTFS. Even if the names are in the Windows Registry, they should be in the captured disk image (image E01). I need to find information about the offset where the Name structure is located (just as there are Descriptor List offsets, Catalog offsets, and many other offsets in your specification).

**Comment by joachimmetz** [comment]
> Even if the names are in the Windows Registry, they should be in the captured disk image (image E01).

Not necessarily, volume shadow and restore points are complex sub systems. The on volume structures (volsnap) is only one part of this. 

Note that anything outside the volume structures is out of scope for this project

**Comment by ArtyomAfanasovBS** [comment]
Thanks for the reply! I will try to investigate the snapshot naming structure at my leisure.

**Comment by joachimmetz** [comment]
I'll close this issue for now then and let me know if you found indications that the information is stored as part of the volume structures. We can always reopen.
