### ISSUE TITLE
Missing shadow copy in copy?

### ISSUE THREAD

**Issue by ArtyomAfanasovBS** [libyal/libvshadow#31]
**Issue:**
1. Generate an E01 image split into chunks (using libewf). The size of the chunk doesn't matter.
2. Read the image (using libewf and libvshadow).

One shadow copy is missing in the result.

**Cause:** When reading a chunked E01 image, the MFT data (specifically the zero-entry in the MFT, which describes the MFT itself) is read as zeros. This occurs because one of the snapshots has block descriptors with an offset pointing to null bytes at the MFT.

I examined the offsets for the MFT records in the generated E01 image. I think that when reading a chunked image, a block descriptor is read for one of the snapshots (in my case, the problematic snapshot is only one), which seems to match the non-chunked image. I believe this because the offset of this descriptor points to the MFT record in the non-chunked image, whereas in the chunked image, this same offset points to zero bytes.

**Question:** Could the issue be with how the chunked image is generated using libewf, how the image is read via libewf, or is it an issue with libvshadow?

P.S. If I generate an E01 image for the same logical drive without splitting, the shadow copy is preserved because the MFT data is not zeros.

**Comment by joachimmetz** [comment]
All ewf files are "chunked" do you mean multiple segment files by any chance? E02, etc.

> When reading a chunked E01 image, the MFT data (specifically the zero-entry in the MFT, which describes the MFT itself) is read as zeros.

Are you sure that information was capture in the original copy? 

Moved this to libvshadow given libewf is just a container format.

**Comment by joachimmetz** [comment]
> P.S. If I generate an E01 image for the same logical drive without splitting, the shadow copy is preserved because the MFT data is not zeros.

which tool do you use to generate the E01 files? what specific command?

**Comment by ArtyomAfanasovBS** [comment]
> All ewf files are "chunked" do you mean multiple segment files by any chance? E02, etc.

Yes, that's right. e01, E02, E03....

> Are you sure that information was capture in the original copy?

Yes, because I captured two images from the same logical drive: a whole image and a chunked image

**Comment by joachimmetz** [comment]
without the necessary details I can only speculate.

which tool do you use to generate the E01 files? what specific commands? what does the raw data in the E01 files look like with different tools?

**Comment by ArtyomAfanasovBS** [comment]
>what does the raw data in the E01 files look like with different tools?

Could you please clarify what specific information you're looking for? I can open the E01 image (both whole and chunked) using FTK Imager. Do you need a particular segment of raw data in hexadecimal?

>which tool do you use to generate the E01 files? what specific commands?

I’ll provide those details a bit later.

**Comment by joachimmetz** [comment]
> Could you please clarify what specific information you're looking for? I can open the E01 image (both whole and chunked) using FTK Imager. Do you need a particular segment of raw data in hexadecimal?

I would be good to confirm the data is actually in the image. I've seen volsnap devices behave unpredictable. E.g. what does debug output tell you https://github.com/libyal/libvshadow/wiki/Troubleshooting#format-or-behavioral-errors ?

**Comment by ArtyomAfanasovBS** [comment]
Strangely, vshadowinfo in Ubunut cannot find shadow copies in an image that is **not** chunked.

Used command:
`vshadowinfo image.e01`

Output:
![image](https://github.com/user-attachments/assets/1f5241f2-4334-4a36-84c9-8deccd589c47)

Raw data of the `image.e01` in FTKImager shows that shadow copies are still present (see offset 0x1e00):
<img width="666" alt="Untitled" src="https://github.com/user-attachments/assets/061cac22-8197-40a8-b008-e75d5870b371">

**Comment by ArtyomAfanasovBS** [comment]
> Strangely, vshadowinfo in Ubunut cannot find shadow copies in an image that is **not** chunked.
> 
> Used command: `vshadowinfo image.e01`
> 
> Output: ![image](https://private-user-images.githubusercontent.com/79638564/378776987-1f5241f2-4334-4a36-84c9-8deccd589c47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTg1MTUsIm5iZiI6MTcyOTY1ODIxNSwicGF0aCI6Ii83OTYzODU2NC8zNzg3NzY5ODctMWY1MjQxZjItNDMzNC00YTM2LTg0YzktOGRlY2NkNTg5YzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA0MzY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNTZlYzQwMDE4MDM2YTQ1YzYzMjYxYzllZTkwZTI3YzllNmQ3MDdlYzMxY2IwYzZmOGQ4OTVhY2FiMDlkMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Oz22q-kJILQ_NZtBH5MaBqhNgDfWRdXkPbRyxmVZtrc)
> 
> Raw data of the `image.e01` in FTKImager shows that shadow copies are still present (see offset 0x1e00): <img alt="Untitled" width="666" src="https://private-user-images.githubusercontent.com/79638564/378778906-061cac22-8197-40a8-b008-e75d5870b371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTg1MTUsIm5iZiI6MTcyOTY1ODIxNSwicGF0aCI6Ii83OTYzODU2NC8zNzg3Nzg5MDYtMDYxY2FjMjItODE5Ny00MGE4LWIwMDgtZTc1ZDU4NzBiMzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA0MzY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiM2U1NTEzY2YzMmZhZDAwZTFjMDM4M2VlYjkzYjc0NmIyZDVmZjA3YjE4ZmRiYjE2NDY3MTlmZGFmMzMxZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cUHovhOKdKa5ZmRoxvq1SMy-yWQvWMfoGfxsGAQ8UM8">

Oh. I was able to find shadow copies information via vshadowinfo for my e01 image (not chunked and chunked). But first it required converting the e01 to a raw representation. And then use the vshadowinfo command for the raw file.

**Comment by joachimmetz** [comment]
> But first it required converting the e01 to a raw representation. And then use the vshadowinfo command for the raw file.

were you running vshadowinfo directly on the E01 file? yeah that is not how the tool is designed to work
