### ISSUE TITLE
libvshadow performance degradation with multithread support

### ISSUE THREAD

**Issue by zweger** [libyal/libvshadow#7]
I've noticed that in certain circumstances, libvshadow can be awfully slow to access VSCs, and consumes a large number of system handles (locks) in the process. These locks are held by `libcdata_list` objects, which are used by the `libcdata_btree` objects used in libvshadow. This is clearly not needed, as libvshadow itself maintains locks around libvshadow volume objects for thread safety.

So, as a workaround, disabling multithread support when compiling libcdata gives greatly improved performance. This is maybe more of an issue for libcdata - but I think we should consider ways to better support libvshadow from libcdata. Perhaps only the root of a libcdata btree should maintain a lock, and the child elements should forego locking, even if multithread support is enabled?

**Comment by joachimmetz** [comment]
> So, as a workaround, disabling multithread support when compiling libcdata gives greatly improved performance. 
> Perhaps only the root of a libcdata btree should maintain a lock, and the child elements should forego locking, even if multithread support is enabled?

instead compile it into libvshadow instead of using libcdata as a shared library.
