### ISSUE TITLE
Can't retrieve certain store metadata after 31st snapshot

### ISSUE THREAD

**Issue by diazfran** [libyal/libvshadow#9]
I've made a little and quick test program using libvshadow in C++ that does the following:
```
libvshadow_volume_initialize
libvshadow_volume_open_wide
libvshadow_volume_get_number_of_stores

for store in stores
    libvshadow_volume_get_store
    libvshadow_store_get_copy_identifier
    libvshadow_volume_get_store_identifier
    libvshadow_store_get_number_of_blocks

    libvshadow_store_free

libvshadow_volume_free
```

For every call there are appropriate error control routines
```
libvshadow_error_sprint
libvshadow_error_backtrace_sprint
```
And I just print the information on console.

###### The environment:
* I've built the library using Visual Studio 2010 and run in Windows: everything works fine
* I'm using this little program on a spare live volume so I pass something like `\\?\Volume{e5766785-278e-477f-8716-5730fbbe3d35}` to `libvshadow_volume_open_wide` and it works well
* I use `vssadmin` to create and delete snapshots
* I've ran these experiments on one Windows 10 and two Windows Server 2012, vanilla virtual machines, default writers and providers, unlimited shadow storage area

###### The experiment:
1. I start with some files in the volume, no snapshots there. I run the program and I get the obvious results: successfully opened volume, no stores.
2. Then I start taking snapshots: any snapshot type is fine. After every couple of snapshots I run this test program and everything works flawlessly: I get the number of stores (for now, the same number of snapshots), I get the store copy identifier and the store identifier as well as the number of blocks for that store. I've also managed to get all the other parameters and available calls in the library.
3. When I take the 32nd snapshot (we have snapshots from 0 to 31)
`libvshadow_volume_get_store` succeeds
`libvshadow_store_get_copy_identifier` fails, the error is empty and the backtrace as well
`libvshadow_volume_get_store_identifier` succeeds
`libvshadow_store_get_number_of_blocks` fails, the error is `libvshadow_store_get_number_of_blocks: unable to retrieve number of blocks store descriptor 31` and the backtrace is `libvshadow_store_descriptor_get_number_of_blocks: invalid store descriptor - missing in-volume store data`
I don't expect `libvshadow_store_get_number_of_blocks` to succeed but it may shed some light on the former error. The `in-volume store data` is there and I can tell by the result of `libvshadow_volume_get_store_identifier`

Now things get a little more interesting:
4. If I keep taking snapshots then `libvshadow_volume_get_number_of_stores` won't return more than 32 stores.
5. After passing the 32nd store, every time I run this program the results are the same. Same stores, same error. If I start deleting snapshots in between the first one and the last one I get the same results: same error, same store. I know that, internally, If I delete snapshots in between the oldest and the newest, stores remain the same, so I didn't expect this to change.
6. If I start deleting snapshots in order, from the beginning (let's say snapshot 0, then 1, etc) then the number of stores decreases and `libvshadow_volume_get_number_of_stores` reflects what's actually on `<Volume>\System Volume Information`. However, the failure persists as in point `3` but in the last store (e.g. if I deleted the first 3, there should be 29 stores, so it fails in store 28)
7. If I start taking snapshots again, then `libvshadow_volume_get_number_of_stores` reflects the correct number of stores until store 31 again.
8. If I keep taking snapshots then the number freezes to 32 stores again like in point `5` but in contrast to point `3` it doesn't fail at `libvshadow_store_get_copy_identifier` nor `libvshadow_store_get_number_of_blocks`

###### Remarks:
I've achieved this situation several times in three different systems. It is somewhat easy to recreate the problem over and over.
I've seen this program reporting 64 stores once from `libvshadow_volume_get_number_of_stores` in an unattended system that autonomously takes snapshots over time, but it still stuck in that number (wouldn't increase with subsequent snapshots) An inspection on `<Volume>\System Volume Information` revealed more than a hundred of stores for that volume

**Comment by joachimmetz** [comment]
Thx for the report having a look when time permits

**Comment by hmahoney** [comment]
I am having the same problem. I am using libvshadow-alpha-20161111.tar.gz. Based on the date of the original post and your response, I assume updating to the current version does not solve this issue.

Not to be pushy, but could you point me to the area of the code to look through to try to find this bug. Of course, I would be happy to send any solution I find on to you.

**Comment by joachimmetz** [comment]
Any test data or format debug information that  can be shared and I could have a look at?

**Comment by hmahoney** [comment]
I am sorry. I am no longer with the company that has this problem, so I no longer have access to that disk image.

You can contact Kevin McCoy (kevin@accessdata.com <mailto:kevin@accessdata.com>). I have contacted him with a brief background and he should be able to help.

Harry Mahoney

**Comment by joachimmetz** [comment]
@hmahoney thanks I'll give that a try later this week

**Comment by joachimmetz** [comment]
Currently in conversation with Kevin McCoy to see what is possible.

**Comment by hmahoney** [comment]
I was just called back by my old employer (AccessData) this week. I have found the image file set that exhibits the problem. it is from a customer. It is a 500GB drive image broken into 318 files. A 7zip file of it is 180GB.

Do have some where I can upload it?

Harry

**Comment by joachimmetz** [comment]
Harry could you contact me via email joachim.metz @ gmail.com

**Comment by joachimmetz** [comment]
Created test file with https://github.com/dfirlabs/vss-specimens/blob/master/generate-speciments.bat.

**Comment by joachimmetz** [comment]
Changes that work on the test image https://github.com/libyal/libvshadow/commit/2e33f76c007bf7fd44665a23db27bb45e99810ac
